api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (ComponentsViewSet, FavoriteViewSet, FollowViewSet,
                    PurchasesViewSet)

router_v1 = DefaultRouter()

router_v1.register('subscriptions', FollowViewSet, basename='subscriptions')
router_v1.register('favorites', FavoriteViewSet, basename='favorites')
router_v1.register('purchases', PurchasesViewSet, basename='purchases')
router_v1.register('ingredients', ComponentsViewSet, basename='ingredients')


urlpatterns = [
    path('v1/', include(router_v1.urls)), ]

foodgram-project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    # ссылки на кастомные страницы ошибок
    path('500/', views.server_error, name='500'),
    path('404/', views.page_not_found, name='404'),
    # регистрация и авторизация
    path('auth/', include('users.urls')),
    # если нужного шаблона для /auth не нашлось в файле users.urls —
    # ищем совпадения в файле django.contrib.auth.urls
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    # ссылки на информацию о сайте
    path('about-author/', views.AboutAuthor.as_view(), name='about_author'),
    path('about-tech/', views.AboutTech.as_view(), name='about_tech'),
    path('', include('prod_h.urls')),

]

handler404 = 'foodgram-project.views.page_not_found'
handler500 = 'foodgram-project.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    # регистрация и авторизация
    path('auth/', include('users.urls')),
    # если нужного шаблона для /auth не нашлось в файле users.urls —
    # ищем совпадения в файле django.contrib.auth.urls
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    # ссылки на информацию о сайте
    path('about-author/', views.AboutAuthor.as_view(), name='about_author'),
    path('about-tech/', views.AboutTech.as_view(), name='about_tech'),
    path('', include('prod_h.urls')),

]

handler404 = 'foodgram.views.page_not_found'
handler500 = 'foodgram.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

foodgram/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path() для страницы регистрации нового пользователя
    # её полный адрес будет auth/signup/, но префикс auth/ обрабатывется в головном urls.py
    path('signup/', views.SignUp.as_view(), name='signup')
]

foodgram/prod_h/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class ListOfIngridients(models.Model):
    # Таблица компонентов
    name = models.CharField(max_length=50,
                            unique=True,
                            verbose_name='Название ингредиента',
                            help_text='Название ингредиента, максимум 50 символов',
                            )
    units_of_measurement = models.CharField(max_length=20,
                                            verbose_name='Единица измерения',
                                            help_text='Единица измерения, максимум 20 симоволов',
                                            )

    def __str__(self):
        return f'{self.name} ({self.units_of_measurement})'

class Teg(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='автор рецепта',
    )
    name = models.CharField(
        max_length=100,
        verbose_name='Название рецепта',
        help_text='Максимальная длинна 100 символов',)
    image = models.ImageField(upload_to='prod_h/', blank=True, null=True)
    text = models.TextField(
        blank=True,
        verbose_name='Описание',
        help_text='Описание рецепта',)
    ingridients = models.ManyToManyField(
        ListOfIngridients,
        through='Ingridient',
        through_fields=('recipe', 'name'),
        verbose_name='Игредиенты',
        help_text='Игредиенты',)
    teg = models.ManyToManyField(Teg,)
    time = models.IntegerField(verbose_name='Вермя приготовления')
    pub_date = models.DateTimeField("date published", auto_now_add=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.name

class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorites',
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='favorite',
    )

class Ingridient(models.Model):
    name = models.ForeignKey(ListOfIngridients,
                             on_delete=models.CASCADE,
                             related_name='ingridient_name',)
    #units_of_measurement = models.ManyToManyField(ListOfIngridients,)
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE,
        related_name="recipe_ingredients",
        verbose_name='Рецепт',
    )
    counts = models.PositiveSmallIntegerField(verbose_name='количество',
        default=1)

    def __str__(self):
        return self.name.name

class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_subscription')
            ]
        verbose_name_plural = "Подписка"

class Cart(models.Model):
    item = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
    )
    customer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='purchases',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['item', 'customer'],
                                    name='unique_purchase')
        ]
        verbose_name_plural = "Корзина"

foodgram/prod_h/forms.py
from django import forms
from .models import Recipe, Teg

class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ['name', 'time', 'text', 'image', 'ingridients', "teg",]

foodgram/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#создадим собственный класс для формы регистрации
#сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

foodgram/prod_h/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.http import HttpResponse

#from .models import Recipe, User
from prod_h.models import Recipe, User
from .forms import RecipeForm
from django.contrib.auth.decorators import login_required


def index(request):
    latest = Recipe.objects.order_by('-pub_date')
    paginator = Paginator(latest, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        "indexNotAuth.html",
        {"posts": latest, "page": page, 'paginator': paginator})

def authors_recipes(request, username):
    author = get_object_or_404(User, username=username)
    user_recipe = author.recipes.all()
    paginator = Paginator(user_recipe, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator,
        'author': author,}
    return render(request, "authorRecipe.html", context=context)

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    context = {
        'recipe': recipe,
    }
    return render(request, 'singlePage.html', context=context)

@login_required
def new_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('index')

        return render(request, 'formRecipe.html', {'form': form})
    form = RecipeForm()
    return render(request, 'formRecipe.html', {'form': form})

foodgram/users/views.py
#импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

#функция reverse_lazy позволяет получить URL по параметру "name" функции path()
#берём, тоже пригодится
from django.urls import reverse_lazy

#импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login') #  где login — это параметр "name" в path()
    template_name = "reg.html"

foodgram/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


def page_not_found(request, exception=None):
    return render(request, "misc/404.html", {"path": request.path}, status=404)


def server_error(request):
    return render(request, "misc/500.html", status=500)


class AboutAuthor(TemplateView):
    template_name = "flatpages/about-author.html"


class AboutTech(TemplateView):
    template_name = "flatpages/about-tech.html"

foodgram/templates/authorRecipe.html
{% extends "base.html" %}
{% block title %} Профиль автора {% endblock %}
{% load static %}
{% block static_css %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock %}
{%block content%}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{{author }}</h1>
            <ul class="tags">
                <li class="tags__item">
                    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="#"></a>
                    <span class="tags__label">Завтрак</span>
                </li>
                <li class="tags__item">
                    <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="#"></a>
                    <span for="lunch" class="tags__label">Обед</span>
                </li>
                <li class="tags__item">
                    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="#"></a>
                    <label for="dinner" class="tags__label">Ужин</label>
                </li>
            </ul>

        </div>


<!--        <p style="padding: 0 0 2em 0;"><a class="button button_style_light-blue" href="#">Подписаться на автора</a></p>-->
        <div class="author-subscribe" data-author="323">
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
        </div>
        <div class="card-list">
            {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
            {% endfor %}
        </div>
    </main>
  <script src="./js/components/MainCards.js"></script>

  <script src="./js/components/Purchases.js"></script>
  <script src="./js/components/Favorites.js"></script>
  <script src="./js/components/Subscribe.js"></script>

  <script src="./js/config/config.js"></script>
  <script src="./js/components/AuthorRecipe.js"></script>
  <script src="./js/components/Header.js"></script>

  <script src="./js/api/Api.js"></script>
  <script src="authorRecipe.js"></script>
{%endblock%}

foodgram/templates/base.html
<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Foodgram-project{% endblock %}</title>

    {% block static_css %}
    {% endblock %}
</head>
<body class="body">
  <header class="header">
      {% include 'includes/nav.html' %}
  </header>
  <main class="main container">
          <div class="main__header">
              {% block content %}
              <!-- Содержимое страницы -->
              {% endblock %}
          </div>
          {% if page.has_other_pages %}
              {% include "includes/paginator.html" with page=page paginator=paginator%}
          {% endif %}
  </main>
{% include 'includes/footer.html' %}
</body>
</html>

foodgram/templates/customPage.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Регистрация</title>
    <link rel="stylesheet" href="./pages/index.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="#" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="custom-center-block">
            <p class="custom-text-block">Сообщение пользователю</p>
        <div class="custom-button-block">
            <button class="button button_style_blue">Перейти на главную</button>
        </div>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

foodgram/templates/formChangeRecipe.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Редактирование рецепта</title>
    <link rel="stylesheet" href="./pages/form.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Избранное</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter"></span></li>

            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Выход</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form">
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="name" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="breakfast" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange">
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="lunch" id="id_lunch" class="tags__checkbox tags__checkbox_style_green" checked>
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="dinner" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple" checked>
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>

                    <div class="form__field-group-ingredientes-container">
                        <div class="form__field-item-ingredient" id="ing_3">
                            <span> Оливки 10шт.</span>
                            <span class="form__field-item-delete"></span>
                            <input id="nameIngredient_3" name="nameIngredient_3" type="hidden" value="Оливки">
                            <input id="valueIngredient_3" name="valueIngredient_3" type="hidden" value="10">
                            <input id="unitsIngredient_3" name="unitsIngredient_3" type="hidden" value="шт.">
                        </div>
                        <div class="form__field-item-ingredient" id="ing_2">
                            <span> Картошка 5шт.</span>
                            <span class="form__field-item-delete"></span>
                            <input id="nameIngredient_2" name="nameIngredient_2" type="hidden" value="Картошка">
                            <input id="valueIngredient_2" name="valueIngredient_2" type="hidden" value="5">
                            <input id="unitsIngredient_2" name="unitsIngredient_2" type="hidden" value="шт.">
                        </div>
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="name" class="form__input">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    <input type="file" class="form__file" name="file" id="id_file">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="#" class="form__ingredient-link">Удалить</a>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
<script src="./js/config/config.js"></script>
<script src="./js/components/Header.js"></script>
<script src="./js/utils/debouncing.js"></script>
<script src="./js/api/Api.js"></script>
<script src="formRecipe.js"></script>
</body>
</html>

foodgram/templates/formRecipe.html
{% extends "base.html" %}
{% block title %} Создание рецепта {% endblock %}
{% load static %}
{% block static_css %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="name" class="form__input">
                    <!--{{form.name}}-->
                    {% if form.name.errors %}
                        <span class="form__error">{{ form.name.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="teg" value="breakfast" id="breakfast" class="tags__checkbox tags__checkbox_style_orange">
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="teg" value="lunch" id="lunch" class="tags__checkbox tags__checkbox_style_green" checked>
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="teg" value="dinner" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple" checked>
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    {% if form.teg.errors %}
                      <span class="form__error">{{form.teg.errors}}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">

                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="name" class="form__input">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <input type="file" name="file" id="id_file">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>
</main>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{%endblock%}

foodgram/templates/indexNotAuth.html
{% extends "base.html" %}
{% block title %} Рецепты {% endblock %}
{% load static %}
{% block static_css %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock %}

{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            <ul class="tags">
                <li class="tags__item">
                    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="#"></a>
                    <span class="tags__label">Завтрак</span>
                </li>
                <li class="tags__item">
                    <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="#"></a>
                    <span for="lunch" class="tags__label">Обед</span>
                </li>
                <li class="tags__item">
                    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="#"></a>
                    <label for="dinner" class="tags__label">Ужин</label>
                </li>
            </ul>
        </div>
        <div class="card-list">
            {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
            {% endfor %}
        </div>
    </main>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'indexNotAuth.js' %}"></script>
{%endblock%}